seed: 1

bart_name: "/home/new/lp/Pyproject/bart_large_chinese/"
dataset_name: daily_people
device: '-1'

num_epochs: 30
batch_size: 5
learning_rate: 5e-5
warmup_ratio: 0.01
eval_begin_epoch: 0
src_seq_ratio: 0.8
tgt_max_len: 30
num_beams: 1
length_penalty: 1

use_prompt: True
prompt_len: 30
prompt_dim: 800

freeze_plm: True
learn_weights: True
save_path: "50_model" # 模型保存路径
load_path: null # 模型加载路径，
notes: ''
